import pandas as pd, json, numpy as np

df = pd.read_csv("gan_20k.csv", header=0)   # your current file

# Rename columns (update this map to your true ordering)
df.columns = ["pt_GeV","eta","phi_rad","m_GeV"]

# --- optional: denormalize using your stored scaler params ---
# Example for MinMax on each column:
# mins  = np.array([pt_min, eta_min, phi_min, m_min], dtype=float)
# maxs  = np.array([pt_max, eta_max, phi_max, m_max], dtype=float)
# df = df * (maxs - mins) + mins
# df["phi_rad"] = (df["phi_rad"] + np.pi) % (2*np.pi) - np.pi

df.to_csv("gan_20k_physics.csv", index=False)

# Sidecar metadata makes the CSV self-describing
meta = {
  "columns":[
    {"name":"pt_GeV","unit":"GeV","desc":"Transverse momentum"},
    {"name":"eta","unit":"","desc":"Pseudorapidity"},
    {"name":"phi_rad","unit":"rad","desc":"Azimuth; wrapped [-pi,pi]"},
    {"name":"m_GeV","unit":"GeV","desc":"Invariant mass"}
  ],
  "scaling":"none / or MinMax / or StandardScaler",
  "notes":"Generated by GAN vX.Y on <date> with seed=<seed>"
}
open("gan_20k_physics.meta.json","w").write(json.dumps(meta, indent=2))

import matplotlib.pyplot as plt
for col in ["pt_GeV","eta","phi_rad","m_GeV"]:
    plt.figure(); df[col].hist(bins=60)
    plt.xlabel(col); plt.ylabel("count"); plt.title(f"{col} (GAN)")
    plt.tight_layout(); plt.show()